name: Windows RDP Ngrok

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Download ngrok
        shell: powershell
        run: |
          Invoke-WebRequest "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath ngrok -Force
          .\ngrok\ngrok.exe version

      - name: Auth ngrok
        shell: powershell
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          .\ngrok\ngrok.exe config add-authtoken $env:NGROK_AUTH_TOKEN

      - name: Enable RDP
        shell: powershell
        run: |
          cmd /c "net user vanducdev Cloud@2026 /add"
          cmd /c "net user vanducdev Cloud@2026"
          cmd /c "net user vanducdev /active:yes"

          cmd /c "net localgroup Administrators vanducdev /add"
          cmd /c "net localgroup ""Remote Desktop Users"" vanducdev /add"

          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 0

          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

          sc.exe config TermService start= auto
          net stop TermService /y
          net start TermService

          Write-Host "=== CHECK USER ==="
          net user vanducdev

          Write-Host "=== CHECK RDP SERVICE ==="
          Get-Service TermService

          Write-Host "=== CHECK PORT 3389 ==="
          netstat -ano | findstr 3389

      - name: Start ngrok and keep alive
        shell: powershell
        run: |
          Start-Process -FilePath ".\ngrok\ngrok.exe" -ArgumentList "tcp 3389"

          Start-Sleep -Seconds 20

          $tunnels = Invoke-RestMethod "http://127.0.0.1:4040/api/tunnels"
          $publicUrl = $tunnels.tunnels[0].public_url
          $addr = $publicUrl -replace "tcp://",""

          Write-Host "======================================"
          Write-Host "RDP READY"
          Write-Host "Computer: $addr"
          Write-Host "User: vanducdev"
          Write-Host "Password: Cloud@2026"
          Write-Host "======================================"

          while ($true) {
            Start-Sleep -Seconds 60
          }
