name: Windows VPS (Localtonet TCP - Không Cần Thẻ)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Kích hoạt Remote Desktop và Đổi Mật Khẩu
      run: |
        # Đổi mật khẩu tài khoản mặc định runneradmin
        net user runneradmin "DucYuz@#2010$!"
        
        # Mở tính năng Remote Desktop (RDP) trên Windows Server
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        
    - name: Tải và Khởi chạy Localtonet x64
      run: |
        Write-Host "🚀 Đang tải Localtonet chính thức bản x64..."
        Invoke-WebRequest -Uri "https://localtonet.com/download/localtonet-windows-x64.zip" -OutFile "localtonet.zip"
        
        Write-Host "🚀 Giải nén bộ cài..."
        Expand-Archive -Path "localtonet.zip" -DestinationPath "." -Force
        
        Write-Host "🚀 Khởi chạy hầm RDP công khai..."
        # 🟢 ÔNG ĐIỀN CHÍNH XÁC AUTH_TOKEN LOCALTONET CỦA ÔNG VÀO CHỖ "xxxx" DƯỚI ĐÂY NHA:
        Start-Process ./localtonet.exe -ArgumentList "authtoken OzX6UWcSDwAHMJdeYbjfTVl2t9ro71Bh0" -WindowStyle Hidden
        
        Write-Host "🚀 Đợi 10 giây để hệ thống thiết lập đường truyền..."
        Start-Sleep -s 10

    - name: Treo VPS giữ kết nối sống 6 tiếng
      run: |
        Start-Sleep -s 21600
